sonar.projectKey=[package-name]
sonar.projectName=[Package Display Name]
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.language=php

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.phpstan.reportPaths=phpstan-report.json

sonar.coverage.exclusions=\
    **/tests/**,\
    **/database/migrations/**,\
    **/Nova/**

sonar.cpd.exclusions=\
    **/Nova/**,\
    **/database/migrations/**

sonar.qualitygate.wait=true
